# Physical parameters

dh_parameters:
  d1: 0.089159
  a2: -0.42500
  a3: -0.39225
  d4: 0.10915
  d5: 0.09465
  d6: 0.0823

offsets:
  ur5_shoulder_offset: 0.13585 # measured from model
  ur5_elbow_offset: 0.0165 # measured from model

inertia_parameters:
  ur5_base_mass: 4.0  # This mass might be incorrect
  ur5_shoulder_mass: 3.7000
  ur5_upper_arm_mass: 8.3930
  ur5_upper_arm_inertia_offset: 0.136
  ur5_forearm_mass: 2.2750
  ur5_wrist_1_mass: 1.2190
  ur5_wrist_2_mass: 1.2190
  ur5_wrist_3_mass: 0.1879

  ur5_shoulder_radius: 0.060   # manually measured
  ur5_upper_arm_radius: 0.054  # manually measured
  ur5_elbow_radius: 0.060      # manually measured
  ur5_forearm_radius: 0.040    # manually measured
  ur5_wrist_radius: 0.045      # manually measured

  links:
    ur5_base:
      radius: 0.06
      length: 0.05
    ur5_shoulder:
      radius: 0.075
      length: 0.178
    ur5_upperarm:
      radius: 0.06
      length: 0.425
    ur5_forearm:
      radius: 0.06
      length: 0.39225
    ur5_wrist_1:
      radius: 0.06
      length: 0.12
    ur5_wrist_2:
      radius: 0.06
      length: 0.12
    ur5_wrist_3:
      radius: 0.0375
      length: 0.0345
    ur5_wrist_1:
      radius: 0.06
      length: 0.095
    ur5_wrist_2:
      radius: 0.06
      length: 0.085
    ur5_wrist_3:
      radius: 0.0375
      length: 0.0305

  center_of_mass:
    ur5_shoulder_cog:
      x: 0.0
      y: 0.00193
      z: -0.02561
    ur5_upper_arm_cog:
      x: 0.0
      y: -0.024201
      z: 0.2125
    ur5_forearm_cog:
      x: 0.0
      y: 0.0265
      z: 0.11993
    ur5_wrist_1_cog:
      x: 0.0
      y: 0.110949
      z: 0.01634
    ur5_wrist_2_cog:
      x: 0.0
      y: 0.0018
      z: 0.11099
    ur5_wrist_3_cog:
      x: 0.0
      y: 0.001159
      z: 0.0
