mesh_files:
  ur5_base:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/base.stl"

  ur5_shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/shoulder.stl"

  ur5_upper_arm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/upperarm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/upperarm.stl"
      mesh_files:

  ur5_forearm:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/forearm.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/forearm.stl"

  ur5_wrist_1:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist1.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist1.stl"
    visual_offset: -0.093

  ur5_wrist_2:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist2.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist2.stl"
    visual_offset: -0.095

  ur5_wrist_3:
    visual:
      mesh: "package://ur_description/meshes/ur5/visual/wrist3.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5/collision/wrist3.stl"
    visual_offset: -0.0818
